### ISSUE TITLE
Las propiedades del modelo, deben llamarse exactamente igual a la Tarea asignada.

### ISSUE THREAD

**Issue by DjMarte** [JendriHidalgo0014/RegistroTecnico#2]
https://github.com/JendriHidalgo0014/RegistroTecnico/blob/419f750eefa2543dcd929b297aa19337a34abe46/Models/Tecnicos.cs#L8

**Comment by JendriHidalgo0014** [comment]
Se modificaron las propiedades del modelo, quedando exactamente como lo pide la tarea.  public int TecnicoId { get; set; }
