### ISSUE TITLE
Falta un await y el método ToList, debe de ir asíncrono

### ISSUE THREAD

**Issue by DjMarte** [JendriHidalgo0014/RegistroTecnico#3]
https://github.com/JendriHidalgo0014/RegistroTecnico/blob/419f750eefa2543dcd929b297aa19337a34abe46/Service/TecnicoService.cs#L59-L61

**Comment by JendriHidalgo0014** [comment]
Se corrijio el metodo y se agrego el await. return await _context.Tecnicos.AsNoTracking()
   .Where(criterio)
   .ToListAsync();
