### ISSUE TITLE
Uso incorrecto de la tildes, lo ideal es usar "&eacute;"

### ISSUE THREAD

**Issue by DjMarte** [JendriHidalgo0014/RegistroTecnico#5]
https://github.com/JendriHidalgo0014/RegistroTecnico/blob/419f750eefa2543dcd929b297aa19337a34abe46/Components/Pages/TecnicosPage/Index.razor#L9

**Comment by JendriHidalgo0014** [comment]
La tilde a sido corregida: <h3 class="bi bi-person-fill"><strong> Registro de T&eacute;cnicos</strong></h3>
