### ISSUE TITLE
No compila

### ISSUE THREAD

**Issue by enelramon** [JendriHidalgo0014/RegistroTecnico#6]
Error en la rama tipo tecnico
![image](https://github.com/user-attachments/assets/d512fa19-2784-4896-8f4d-f010c3e4f6f4)

Error en la rama master
![image](https://github.com/user-attachments/assets/639ff762-4e15-4ece-95b2-5ef5dc6dc3de)

**Comment by JendriHidalgo0014** [comment]
Ya resolvi el problema. Puede verificar nuevamente.
